version: '3'

services:

  server:
    build:
      context: ./load-balancer
    restart: always
    links:
      - app
    ports:
      - 80:80

  app:
    build:
      context: ./app
    restart: always
    environment:
      - PORT=9001
