version: '3'

services:

  server:
    build:
      context: ./load-balancer
    restart: always
    links:
      - app
    ports:
      - 9000:80

  app:
    build:
      context: ./app
    restart: always
    ports:
      - 9001:9001
    environment:
      - PORT=9001

networks:
  default:
    external:
      name: nginx-proxy
